version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/exist_id_server/
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/server2/scripts
    pattern: "*.sh"
    mode: 777
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: root
