// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: personInfo_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number    int32  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Avenue    string `protobuf:"bytes,2,opt,name=avenue,proto3" json:"avenue,omitempty"`
	Quartier  string `protobuf:"bytes,3,opt,name=quartier,proto3" json:"quartier,omitempty"`
	Commune   string `protobuf:"bytes,4,opt,name=commune,proto3" json:"commune,omitempty"` // we can further make this of type Enum since we know all the possible communes
	ZipCode   string `protobuf:"bytes,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Province  string `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"` // can be an Enum as well
	Ville     string `protobuf:"bytes,7,opt,name=ville,proto3" json:"ville,omitempty"`
	Reference string `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"` // reference is optional. this is just to help with easier localisation
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Address) GetAvenue() string {
	if x != nil {
		return x.Avenue
	}
	return ""
}

func (x *Address) GetQuartier() string {
	if x != nil {
		return x.Quartier
	}
	return ""
}

func (x *Address) GetCommune() string {
	if x != nil {
		return x.Commune
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetVille() string {
	if x != nil {
		return x.Ville
	}
	return ""
}

func (x *Address) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type Names struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nom         string   `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom      string   `protobuf:"bytes,2,opt,name=prenom,proto3" json:"prenom,omitempty"`
	MiddleNames []string `protobuf:"bytes,3,rep,name=middle_names,json=middleNames,proto3" json:"middle_names,omitempty"`
}

func (x *Names) Reset() {
	*x = Names{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Names) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Names) ProtoMessage() {}

func (x *Names) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Names.ProtoReflect.Descriptor instead.
func (*Names) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Names) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *Names) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *Names) GetMiddleNames() []string {
	if x != nil {
		return x.MiddleNames
	}
	return nil
}

type Origin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province []string `protobuf:"bytes,1,rep,name=province,proto3" json:"province,omitempty"` // could be from multiple provinces
	ChefLieu string   `protobuf:"bytes,2,opt,name=chef_lieu,json=chefLieu,proto3" json:"chef_lieu,omitempty"`
}

func (x *Origin) Reset() {
	*x = Origin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Origin) GetProvince() []string {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *Origin) GetChefLieu() string {
	if x != nil {
		return x.ChefLieu
	}
	return ""
}

type Phenotype struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height   float32 `protobuf:"fixed32,1,opt,name=height,proto3" json:"height,omitempty"`
	Weight   float32 `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	EyeColor string  `protobuf:"bytes,3,opt,name=eye_color,json=eyeColor,proto3" json:"eye_color,omitempty"`
}

func (x *Phenotype) Reset() {
	*x = Phenotype{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phenotype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phenotype) ProtoMessage() {}

func (x *Phenotype) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phenotype.ProtoReflect.Descriptor instead.
func (*Phenotype) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{3}
}

func (x *Phenotype) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Phenotype) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Phenotype) GetEyeColor() string {
	if x != nil {
		return x.EyeColor
	}
	return ""
}

// We have to look further on how to represent images in proto files
// Also have to find a good way of representing finger print as a stream of bytes or something else
type Biometric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Photos      []byte `protobuf:"bytes,1,opt,name=photos,proto3" json:"photos,omitempty"`
	FingerPrint []byte `protobuf:"bytes,2,opt,name=finger_print,json=fingerPrint,proto3" json:"finger_print,omitempty"`
}

func (x *Biometric) Reset() {
	*x = Biometric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biometric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biometric) ProtoMessage() {}

func (x *Biometric) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biometric.ProtoReflect.Descriptor instead.
func (*Biometric) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{4}
}

func (x *Biometric) GetPhotos() []byte {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Biometric) GetFingerPrint() []byte {
	if x != nil {
		return x.FingerPrint
	}
	return nil
}

type DateOfBirth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Month string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Year  string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *DateOfBirth) Reset() {
	*x = DateOfBirth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateOfBirth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateOfBirth) ProtoMessage() {}

func (x *DateOfBirth) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateOfBirth.ProtoReflect.Descriptor instead.
func (*DateOfBirth) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{5}
}

func (x *DateOfBirth) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DateOfBirth) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *DateOfBirth) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

// might some performance consequence but I will into it later
type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{6}
}

func (x *UUID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day   int32 `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{7}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type CardValidity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssueDate      *Date `protobuf:"bytes,1,opt,name=IssueDate,proto3" json:"IssueDate,omitempty"`
	ExpirationDate *Date `protobuf:"bytes,2,opt,name=ExpirationDate,proto3" json:"ExpirationDate,omitempty"`
}

func (x *CardValidity) Reset() {
	*x = CardValidity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardValidity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardValidity) ProtoMessage() {}

func (x *CardValidity) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardValidity.ProtoReflect.Descriptor instead.
func (*CardValidity) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{8}
}

func (x *CardValidity) GetIssueDate() *Date {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *CardValidity) GetExpirationDate() *Date {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

type PersonInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names       *Names       `protobuf:"bytes,1,opt,name=names,proto3" json:"names,omitempty"`
	Biometrics  *Biometric   `protobuf:"bytes,2,opt,name=biometrics,proto3" json:"biometrics,omitempty"`
	Address     *Address     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Origins     *Origin      `protobuf:"bytes,4,opt,name=origins,proto3" json:"origins,omitempty"`
	Phenotypes  *Phenotype   `protobuf:"bytes,5,opt,name=phenotypes,proto3" json:"phenotypes,omitempty"`
	DateOfBirth *DateOfBirth `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
}

func (x *PersonInfoRequest) Reset() {
	*x = PersonInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfoRequest) ProtoMessage() {}

func (x *PersonInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfoRequest.ProtoReflect.Descriptor instead.
func (*PersonInfoRequest) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{9}
}

func (x *PersonInfoRequest) GetNames() *Names {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PersonInfoRequest) GetBiometrics() *Biometric {
	if x != nil {
		return x.Biometrics
	}
	return nil
}

func (x *PersonInfoRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PersonInfoRequest) GetOrigins() *Origin {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *PersonInfoRequest) GetPhenotypes() *Phenotype {
	if x != nil {
		return x.Phenotypes
	}
	return nil
}

func (x *PersonInfoRequest) GetDateOfBirth() *DateOfBirth {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

type PersonInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names        *Names        `protobuf:"bytes,1,opt,name=names,proto3" json:"names,omitempty"`
	Biometrics   *Biometric    `protobuf:"bytes,2,opt,name=biometrics,proto3" json:"biometrics,omitempty"`
	Address      *Address      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Origins      *Origin       `protobuf:"bytes,4,opt,name=origins,proto3" json:"origins,omitempty"`
	Phenotypes   *Phenotype    `protobuf:"bytes,5,opt,name=phenotypes,proto3" json:"phenotypes,omitempty"`
	DateOfBirth  *DateOfBirth  `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	CardValidity *CardValidity `protobuf:"bytes,7,opt,name=card_validity,json=cardValidity,proto3" json:"card_validity,omitempty"`
	UUID         *UUID         `protobuf:"bytes,8,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (x *PersonInfoResponse) Reset() {
	*x = PersonInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfoResponse) ProtoMessage() {}

func (x *PersonInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfoResponse.ProtoReflect.Descriptor instead.
func (*PersonInfoResponse) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{10}
}

func (x *PersonInfoResponse) GetNames() *Names {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PersonInfoResponse) GetBiometrics() *Biometric {
	if x != nil {
		return x.Biometrics
	}
	return nil
}

func (x *PersonInfoResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PersonInfoResponse) GetOrigins() *Origin {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *PersonInfoResponse) GetPhenotypes() *Phenotype {
	if x != nil {
		return x.Phenotypes
	}
	return nil
}

func (x *PersonInfoResponse) GetDateOfBirth() *DateOfBirth {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *PersonInfoResponse) GetCardValidity() *CardValidity {
	if x != nil {
		return x.CardValidity
	}
	return nil
}

func (x *PersonInfoResponse) GetUUID() *UUID {
	if x != nil {
		return x.UUID
	}
	return nil
}

type EditPersonInfoParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonId         *UUID               `protobuf:"bytes,1,opt,name=personId,proto3" json:"personId,omitempty"`
	EditedPersonInfo *PersonInfoResponse `protobuf:"bytes,2,opt,name=editedPersonInfo,proto3" json:"editedPersonInfo,omitempty"`
}

func (x *EditPersonInfoParameters) Reset() {
	*x = EditPersonInfoParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditPersonInfoParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPersonInfoParameters) ProtoMessage() {}

func (x *EditPersonInfoParameters) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPersonInfoParameters.ProtoReflect.Descriptor instead.
func (*EditPersonInfoParameters) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{11}
}

func (x *EditPersonInfoParameters) GetPersonId() *UUID {
	if x != nil {
		return x.PersonId
	}
	return nil
}

func (x *EditPersonInfoParameters) GetEditedPersonInfo() *PersonInfoResponse {
	if x != nil {
		return x.EditedPersonInfo
	}
	return nil
}

var File_personInfo_msg_proto protoreflect.FileDescriptor

var file_personInfo_msg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xda, 0x01, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x72, 0x74, 0x69,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x72, 0x74, 0x69,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x54, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x41, 0x0a,
	0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x66, 0x5f, 0x6c, 0x69, 0x65, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x66, 0x4c, 0x69, 0x65, 0x75,
	0x22, 0x58, 0x0a, 0x09, 0x50, 0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x65, 0x79, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x46, 0x0a, 0x09, 0x42, 0x69,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x50, 0x72, 0x69,
	0x6e, 0x74, 0x22, 0x49, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x1a, 0x0a,
	0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x68, 0x0a,
	0x0c, 0x43, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a,
	0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x09, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x94, 0x02, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x2d,
	0x0a, 0x0a, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x52, 0x0a, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x25, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x52, 0x07, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x70, 0x68,
	0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70,
	0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x0d, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x22, 0xea,
	0x02, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x0a, 0x62, 0x69, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x07,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x07, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x70, 0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x68, 0x65, 0x6e,
	0x6f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x33, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x35, 0x0a, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52,
	0x0c, 0x63, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a,
	0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22, 0x84, 0x01, 0x0a, 0x18,
	0x45, 0x64, 0x69, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x42,
	0x0a, 0x10, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x10, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_personInfo_msg_proto_rawDescOnce sync.Once
	file_personInfo_msg_proto_rawDescData = file_personInfo_msg_proto_rawDesc
)

func file_personInfo_msg_proto_rawDescGZIP() []byte {
	file_personInfo_msg_proto_rawDescOnce.Do(func() {
		file_personInfo_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_personInfo_msg_proto_rawDescData)
	})
	return file_personInfo_msg_proto_rawDescData
}

var file_personInfo_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_personInfo_msg_proto_goTypes = []interface{}{
	(*Address)(nil),                  // 0: pb.Address
	(*Names)(nil),                    // 1: pb.Names
	(*Origin)(nil),                   // 2: pb.Origin
	(*Phenotype)(nil),                // 3: pb.Phenotype
	(*Biometric)(nil),                // 4: pb.Biometric
	(*DateOfBirth)(nil),              // 5: pb.DateOfBirth
	(*UUID)(nil),                     // 6: pb.UUID
	(*Date)(nil),                     // 7: pb.Date
	(*CardValidity)(nil),             // 8: pb.CardValidity
	(*PersonInfoRequest)(nil),        // 9: pb.PersonInfoRequest
	(*PersonInfoResponse)(nil),       // 10: pb.PersonInfoResponse
	(*EditPersonInfoParameters)(nil), // 11: pb.EditPersonInfoParameters
}
var file_personInfo_msg_proto_depIdxs = []int32{
	7,  // 0: pb.CardValidity.IssueDate:type_name -> pb.Date
	7,  // 1: pb.CardValidity.ExpirationDate:type_name -> pb.Date
	1,  // 2: pb.PersonInfoRequest.names:type_name -> pb.Names
	4,  // 3: pb.PersonInfoRequest.biometrics:type_name -> pb.Biometric
	0,  // 4: pb.PersonInfoRequest.address:type_name -> pb.Address
	2,  // 5: pb.PersonInfoRequest.origins:type_name -> pb.Origin
	3,  // 6: pb.PersonInfoRequest.phenotypes:type_name -> pb.Phenotype
	5,  // 7: pb.PersonInfoRequest.date_of_birth:type_name -> pb.DateOfBirth
	1,  // 8: pb.PersonInfoResponse.names:type_name -> pb.Names
	4,  // 9: pb.PersonInfoResponse.biometrics:type_name -> pb.Biometric
	0,  // 10: pb.PersonInfoResponse.address:type_name -> pb.Address
	2,  // 11: pb.PersonInfoResponse.origins:type_name -> pb.Origin
	3,  // 12: pb.PersonInfoResponse.phenotypes:type_name -> pb.Phenotype
	5,  // 13: pb.PersonInfoResponse.date_of_birth:type_name -> pb.DateOfBirth
	8,  // 14: pb.PersonInfoResponse.card_validity:type_name -> pb.CardValidity
	6,  // 15: pb.PersonInfoResponse.UUID:type_name -> pb.UUID
	6,  // 16: pb.EditPersonInfoParameters.personId:type_name -> pb.UUID
	10, // 17: pb.EditPersonInfoParameters.editedPersonInfo:type_name -> pb.PersonInfoResponse
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_personInfo_msg_proto_init() }
func file_personInfo_msg_proto_init() {
	if File_personInfo_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_personInfo_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Names); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Origin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phenotype); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biometric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateOfBirth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardValidity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditPersonInfoParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personInfo_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_personInfo_msg_proto_goTypes,
		DependencyIndexes: file_personInfo_msg_proto_depIdxs,
		MessageInfos:      file_personInfo_msg_proto_msgTypes,
	}.Build()
	File_personInfo_msg_proto = out.File
	file_personInfo_msg_proto_rawDesc = nil
	file_personInfo_msg_proto_goTypes = nil
	file_personInfo_msg_proto_depIdxs = nil
}
