// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.9.2
// source: personInfo_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number    int32  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Avenue    string `protobuf:"bytes,2,opt,name=avenue,proto3" json:"avenue,omitempty"`
	Quartier  string `protobuf:"bytes,3,opt,name=quartier,proto3" json:"quartier,omitempty"`
	Commune   string `protobuf:"bytes,4,opt,name=commune,proto3" json:"commune,omitempty"` // we can further make this of type Enum since we know all the possible communes
	ZipCode   string `protobuf:"bytes,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Province  string `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"` // can be an Enum as well
	Ville     string `protobuf:"bytes,7,opt,name=ville,proto3" json:"ville,omitempty"`
	Reference string `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"` // reference is optional. this is just to help with easier localisation
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Address) GetAvenue() string {
	if x != nil {
		return x.Avenue
	}
	return ""
}

func (x *Address) GetQuartier() string {
	if x != nil {
		return x.Quartier
	}
	return ""
}

func (x *Address) GetCommune() string {
	if x != nil {
		return x.Commune
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetVille() string {
	if x != nil {
		return x.Ville
	}
	return ""
}

func (x *Address) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type Names struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nom         string   `protobuf:"bytes,1,opt,name=nom,proto3" json:"nom,omitempty"`
	PostNom     string   `protobuf:"bytes,2,opt,name=post_nom,json=postNom,proto3" json:"post_nom,omitempty"`
	MiddleNames []string `protobuf:"bytes,3,rep,name=middle_names,json=middleNames,proto3" json:"middle_names,omitempty"`
}

func (x *Names) Reset() {
	*x = Names{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Names) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Names) ProtoMessage() {}

func (x *Names) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Names.ProtoReflect.Descriptor instead.
func (*Names) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Names) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *Names) GetPostNom() string {
	if x != nil {
		return x.PostNom
	}
	return ""
}

func (x *Names) GetMiddleNames() []string {
	if x != nil {
		return x.MiddleNames
	}
	return nil
}

type Origin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province []string `protobuf:"bytes,1,rep,name=province,proto3" json:"province,omitempty"` // could be from multiple provinces
	ChefLieu string   `protobuf:"bytes,2,opt,name=chef_lieu,json=chefLieu,proto3" json:"chef_lieu,omitempty"`
}

func (x *Origin) Reset() {
	*x = Origin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Origin) GetProvince() []string {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *Origin) GetChefLieu() string {
	if x != nil {
		return x.ChefLieu
	}
	return ""
}

type Phenotype struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height   float32 `protobuf:"fixed32,1,opt,name=height,proto3" json:"height,omitempty"`
	Weight   float32 `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	EyeColor string  `protobuf:"bytes,3,opt,name=eye_color,json=eyeColor,proto3" json:"eye_color,omitempty"`
}

func (x *Phenotype) Reset() {
	*x = Phenotype{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phenotype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phenotype) ProtoMessage() {}

func (x *Phenotype) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phenotype.ProtoReflect.Descriptor instead.
func (*Phenotype) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{3}
}

func (x *Phenotype) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Phenotype) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Phenotype) GetEyeColor() string {
	if x != nil {
		return x.EyeColor
	}
	return ""
}

// We have to look further on how to represent images in proto files
// Also have to find a good way of representing finger print as a stream of bytes or something else
type Biometric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Photos      []byte `protobuf:"bytes,1,opt,name=photos,proto3" json:"photos,omitempty"`
	FingerPrint []byte `protobuf:"bytes,2,opt,name=finger_print,json=fingerPrint,proto3" json:"finger_print,omitempty"`
}

func (x *Biometric) Reset() {
	*x = Biometric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biometric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biometric) ProtoMessage() {}

func (x *Biometric) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biometric.ProtoReflect.Descriptor instead.
func (*Biometric) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{4}
}

func (x *Biometric) GetPhotos() []byte {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Biometric) GetFingerPrint() []byte {
	if x != nil {
		return x.FingerPrint
	}
	return nil
}

type DateOfBirth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Month string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Year  string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *DateOfBirth) Reset() {
	*x = DateOfBirth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateOfBirth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateOfBirth) ProtoMessage() {}

func (x *DateOfBirth) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateOfBirth.ProtoReflect.Descriptor instead.
func (*DateOfBirth) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{5}
}

func (x *DateOfBirth) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DateOfBirth) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *DateOfBirth) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

// might some performance consequence but I will into it later
type UIUD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uiud string `protobuf:"bytes,1,opt,name=uiud,proto3" json:"uiud,omitempty"`
}

func (x *UIUD) Reset() {
	*x = UIUD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIUD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIUD) ProtoMessage() {}

func (x *UIUD) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIUD.ProtoReflect.Descriptor instead.
func (*UIUD) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{6}
}

func (x *UIUD) GetUiud() string {
	if x != nil {
		return x.Uiud
	}
	return ""
}

type PersonInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names       *Names       `protobuf:"bytes,1,opt,name=names,proto3" json:"names,omitempty"`
	Biometrics  *Biometric   `protobuf:"bytes,2,opt,name=biometrics,proto3" json:"biometrics,omitempty"`
	Address     *Address     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Origins     *Origin      `protobuf:"bytes,4,opt,name=origins,proto3" json:"origins,omitempty"`
	Phenotypes  *Phenotype   `protobuf:"bytes,5,opt,name=phenotypes,proto3" json:"phenotypes,omitempty"`
	DateOfBirth *DateOfBirth `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Id          *UIUD        `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PersonInfo) Reset() {
	*x = PersonInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonInfo) ProtoMessage() {}

func (x *PersonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonInfo.ProtoReflect.Descriptor instead.
func (*PersonInfo) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{7}
}

func (x *PersonInfo) GetNames() *Names {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PersonInfo) GetBiometrics() *Biometric {
	if x != nil {
		return x.Biometrics
	}
	return nil
}

func (x *PersonInfo) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PersonInfo) GetOrigins() *Origin {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *PersonInfo) GetPhenotypes() *Phenotype {
	if x != nil {
		return x.Phenotypes
	}
	return nil
}

func (x *PersonInfo) GetDateOfBirth() *DateOfBirth {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *PersonInfo) GetId() *UIUD {
	if x != nil {
		return x.Id
	}
	return nil
}

type EditPersonInfoParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonId         *UIUD       `protobuf:"bytes,1,opt,name=personId,proto3" json:"personId,omitempty"`
	EditedPersonInfo *PersonInfo `protobuf:"bytes,2,opt,name=editedPersonInfo,proto3" json:"editedPersonInfo,omitempty"`
}

func (x *EditPersonInfoParameters) Reset() {
	*x = EditPersonInfoParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditPersonInfoParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPersonInfoParameters) ProtoMessage() {}

func (x *EditPersonInfoParameters) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPersonInfoParameters.ProtoReflect.Descriptor instead.
func (*EditPersonInfoParameters) Descriptor() ([]byte, []int) {
	return file_personInfo_msg_proto_rawDescGZIP(), []int{8}
}

func (x *EditPersonInfoParameters) GetPersonId() *UIUD {
	if x != nil {
		return x.PersonId
	}
	return nil
}

func (x *EditPersonInfoParameters) GetEditedPersonInfo() *PersonInfo {
	if x != nil {
		return x.EditedPersonInfo
	}
	return nil
}

var File_personInfo_msg_proto protoreflect.FileDescriptor

var file_personInfo_msg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xda, 0x01, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x72, 0x74, 0x69,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x72, 0x74, 0x69,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x69, 0x6c, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x57, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x6f, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x4e, 0x6f, 0x6d, 0x12, 0x21, 0x0a,
	0x0c, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x22, 0x41, 0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x66, 0x5f, 0x6c,
	0x69, 0x65, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x66, 0x4c,
	0x69, 0x65, 0x75, 0x22, 0x58, 0x0a, 0x09, 0x50, 0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x79, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x46, 0x0a,
	0x09, 0x42, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x50, 0x72, 0x69, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42,
	0x69, 0x72, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x22, 0x1a, 0x0a, 0x04, 0x55, 0x49, 0x55, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x75, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x75, 0x64, 0x22, 0xa7, 0x02, 0x0a,
	0x0a, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0a,
	0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52,
	0x0a, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52,
	0x07, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x70, 0x68, 0x65, 0x6e,
	0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x68, 0x65, 0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x68, 0x65,
	0x6e, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x52,
	0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x49,
	0x55, 0x44, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7c, 0x0a, 0x18, 0x45, 0x64, 0x69, 0x74, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x49, 0x55, 0x44, 0x52, 0x08,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x10, 0x65, 0x64, 0x69, 0x74,
	0x65, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x10, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_personInfo_msg_proto_rawDescOnce sync.Once
	file_personInfo_msg_proto_rawDescData = file_personInfo_msg_proto_rawDesc
)

func file_personInfo_msg_proto_rawDescGZIP() []byte {
	file_personInfo_msg_proto_rawDescOnce.Do(func() {
		file_personInfo_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_personInfo_msg_proto_rawDescData)
	})
	return file_personInfo_msg_proto_rawDescData
}

var file_personInfo_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_personInfo_msg_proto_goTypes = []interface{}{
	(*Address)(nil),                  // 0: pb.Address
	(*Names)(nil),                    // 1: pb.Names
	(*Origin)(nil),                   // 2: pb.Origin
	(*Phenotype)(nil),                // 3: pb.Phenotype
	(*Biometric)(nil),                // 4: pb.Biometric
	(*DateOfBirth)(nil),              // 5: pb.DateOfBirth
	(*UIUD)(nil),                     // 6: pb.UIUD
	(*PersonInfo)(nil),               // 7: pb.PersonInfo
	(*EditPersonInfoParameters)(nil), // 8: pb.EditPersonInfoParameters
}
var file_personInfo_msg_proto_depIdxs = []int32{
	1, // 0: pb.PersonInfo.names:type_name -> pb.Names
	4, // 1: pb.PersonInfo.biometrics:type_name -> pb.Biometric
	0, // 2: pb.PersonInfo.address:type_name -> pb.Address
	2, // 3: pb.PersonInfo.origins:type_name -> pb.Origin
	3, // 4: pb.PersonInfo.phenotypes:type_name -> pb.Phenotype
	5, // 5: pb.PersonInfo.date_of_birth:type_name -> pb.DateOfBirth
	6, // 6: pb.PersonInfo.id:type_name -> pb.UIUD
	6, // 7: pb.EditPersonInfoParameters.personId:type_name -> pb.UIUD
	7, // 8: pb.EditPersonInfoParameters.editedPersonInfo:type_name -> pb.PersonInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_personInfo_msg_proto_init() }
func file_personInfo_msg_proto_init() {
	if File_personInfo_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_personInfo_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Names); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Origin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phenotype); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biometric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateOfBirth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UIUD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditPersonInfoParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personInfo_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_personInfo_msg_proto_goTypes,
		DependencyIndexes: file_personInfo_msg_proto_depIdxs,
		MessageInfos:      file_personInfo_msg_proto_msgTypes,
	}.Build()
	File_personInfo_msg_proto = out.File
	file_personInfo_msg_proto_rawDesc = nil
	file_personInfo_msg_proto_goTypes = nil
	file_personInfo_msg_proto_depIdxs = nil
}
