name: exist_server_redeploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
      
permissions:
  id-token: write
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Updating the server Code and Redeploying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.ACCESS_KEY_EC2 }}
        script: |
          ssh ec2-user@ec2-18-205-154-46.compute-1.amazonaws.com
          cd /home/ec2-user/server/existe-id/
          git pull
          cd /home/ec2-user/server/existe-id/useraccount/cmd/
          go build main.go -o existserverbinary
          sudo systemctl daemon-reload
          sudo systemctl restart exist_id.service

          
